{"name": "Проверка авторизации незарегистрированного курьера", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 404 and {'code': 404, 'message': 'Учетная запись не найдена'} == {'message': 'Учетная запись не найдена'}\n +  where 404 = <Response [404]>.status_code\n  \n  Common items:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mУчетная запись не найдена\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Left contains 1 more item:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m404\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  \n  Full diff:\n  \u001b[0m\u001b[90m \u001b[39;49;00m {\u001b[90m\u001b[39;49;00m\n  \u001b[92m+     'code': 404,\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  \u001b[90m \u001b[39;49;00m     'message': 'Учетная запись не найдена',\u001b[90m\u001b[39;49;00m\n  \u001b[90m \u001b[39;49;00m }\u001b[90m\u001b[39;49;00m)", "trace": "self = <test_login_courier.TestLoginCourier object at 0x00000163190B5940>, for_reg_delete_cour = {'firstName': 'Евстигней', 'login': 'nosovaalevtina', 'password': 56257168}\n\n    @allure.title('Проверка авторизации незарегистрированного курьера')\n    @allure.description(f'на ручке {Endpoint.login_courier_url}')\n    def test_login_courier_no_reg(self, for_reg_delete_cour):\n        response = requests.post(f'{Endpoint.login_courier_url}', json=for_reg_delete_cour)\n>       assert response.status_code == 404 and response.json() == {\"message\": \"Учетная запись не найдена\"}\nE       AssertionError: assert (404 == 404 and {'code': 404, 'message': 'Учетная запись не найдена'} == {'message': 'Учетная запись не найдена'}\nE        +  where 404 = <Response [404]>.status_code\nE         \nE         Common items:\nE         \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mУчетная запись не найдена\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\nE         Left contains 1 more item:\nE         \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m404\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\nE         \nE         Full diff:\nE         \u001b[0m\u001b[90m \u001b[39;49;00m {\u001b[90m\u001b[39;49;00m\nE         \u001b[92m+     'code': 404,\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\nE         \u001b[90m \u001b[39;49;00m     'message': 'Учетная запись не найдена',\u001b[90m\u001b[39;49;00m\nE         \u001b[90m \u001b[39;49;00m }\u001b[90m\u001b[39;49;00m)\n\ntests\\test_login_courier.py:29: AssertionError"}, "description": "на ручке https://qa-scooter.praktikum-services.ru/api/v1/courier/login", "start": 1754410544953, "stop": 1754410545159, "uuid": "2894a8c0-260d-4846-988c-b83463dcfdaf", "historyId": "52c9127772cd545d11f5e9cfc0338003", "testCaseId": "52c9127772cd545d11f5e9cfc0338003", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_no_reg", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-GVQL230"}, {"name": "thread", "value": "14152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestLoginCourier"]}